### ISSUE TITLE
转换后速度异常

### ISSUE THREAD

**Issue by Meikoday** [yangyang5214/gpx2fit-java#2]
![image](https://github.com/user-attachments/assets/3fe74eb0-2f0c-4cfc-98cd-97a0a9bf8ee5)
UnKnow type road_biking
Find point size 4843
 - sport is CYCLING
 - distance 33.14 km
 - totalMovingTime 4958.00 s
 - totalElapsedTime 5018.00 s
 - totalAscent 324.80 m
 - totalDescent -326.40 ms
Save file to 2.fit
速度没有正确显示是什么原因呢？

**Comment by yangyang5214** [comment]
你的gpx源文件没速度吧

此脚本只会解析 gpx 文件的 speed tag.

https://github.com/yangyang5214/gpx2fit-java/blob/main/src/main/java/com/yangyang5214/gpx2fit/gpx/GpxParser.java#L228

**Comment by yangyang5214** [comment]
@Meikoday  可以体验下微信小程序 gpxt  . 

- 上传的 gpx 文件没速度就会补充下（小程序自己算法）

**Comment by Meikoday** [comment]
> 你的gpx源文件没速度吧
> 
> 此脚本只会解析gpx文件的速度标签。
> 
> https://github.com/yangyang5214/gpx2fit-java/blob/main/src/main/java/com/yangyang5214/gpx2fit/gpx/GpxParser.java#L228

行者导出的gpx没有速度标签，谢谢
